# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/kendo-ui-dev"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock]
exclude_navigation: ["knowledge-base/*"]

## List your directory names and order here, like this:
navigation:
    getting-started:
        title: Getting Started
        position: 1

## Product title
product: "Progress Telerik VR DataViz"
platform: kendo-ui

## The application virtual path
baseurl: /kendo-ui-dev

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "kendo-ui"

has_kb_portal: false
has_api_reference: false

# Feedback Form ID
ff-sheet-id: 111111111111111111

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:ddknw1m8sne'
gcs_api_key: 'AIzaSyCY-QFufu2mx3iNQRGS6zSjjkkI4HNvUTU'

edit_repo_url: https://github.com/telerik/kendo-ui-docs/edit/master

footer:
-
  title: "Getting Started"
  links:
    "Download Now": https://www.telerik.com/download/fiddler-everywhere
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/fiddler
    "Blogs": https://www.telerik.com/blogs/tag/fiddler
    "Feedback Portal": https://feedback.telerik.com/fiddler-everywhere
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/TelerikFiddler/ 

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
